--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-cli)

-- h-lua库
require "h-lua"
-- alias h-lua库别称（参考）
require "scripts.alias"
-- setup 游戏准备
require "scripts.setup"
-- start 游戏主程（必备main函数）
require "scripts.start"