-- h-lua内置slk

--- #单位 token
hslk_unit({
    _parent = "ogru",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_UNIT_TOKEN",
    special = 1,
    abilList = "Avul,Aloc",
    upgrade = "",
    file = ".mdl",
    unitShadow = "",
    collision = 0,
    Art = "",
    movetp = "fly",
    moveHeight = 25.00,
    spd = 522,
    turnRate = 3.00,
    moveFloor = 25.00,
    weapsOn = 0,
    race = "other",
    fused = 0,
    sight = 0,
    nsight = 0,
    Builds = "",
    upgrades = "",
})

--- #冲击单位 token
hslk_unit({
    _parent = "ogru",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_UNIT_TOKEN_LEAP",
    special = 1,
    abilList = "Avul,Aloc",
    upgrade = "",
    file = "h-lua\\interface_token.mdx",
    unitShadow = "",
    collision = 0,
    Art = "",
    modelScale = 1.00,
    movetp = "fly",
    moveHeight = 0.00,
    moveFloor = 0.00,
    spd = 0,
    turnRate = 3.00,
    weapsOn = 0,
    race = "other",
    fused = 0,
    sight = 250,
    nsight = 250,
    Builds = "",
    upgrades = "",
})

-- #眩晕[0.05-0.5]
for during = 1, 10, 1 do
    local swDur = during * 0.05
    hslk_ability({
        _parent = "AHtb",
        EditorSuffix = "#h-lua",
        Name = "H_LUA_SKILL_BREAK_" .. swDur,
        DataA1 = 0.00,
        Tip = "眩晕" .. swDur .. "秒",
        Ubertip = "眩晕" .. swDur .. "秒",
        Art = "",
        Missileart = "",
        Missilespeed = 999999,
        Animnames = "",
        hero = 0,
        race = "other",
        levels = 1,
        Cool1 = 10.00,
        targs1 = "neutral,vulnerable,ground,enemies,invulnerable,organic,debris,air,friend,self",
        Dur1 = swDur,
        HeroDur1 = swDur,
        Cost1 = 0,
        Rng1 = 9999.00,
    })
end

-- #无限眩晕
hslk_ability({
    _parent = "AHtb",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_SKILL_SWIM_UN_LIMIT",
    DataA1 = 0.00,
    Tip = "无限眩晕",
    Ubertip = "无限眩晕",
    Art = "",
    Missileart = "",
    Missilespeed = 999999,
    Missilearc = 0,
    Animnames = "",
    hero = 0,
    race = "other",
    levels = 1,
    Cool1 = 10,
    targs1 = "neutral,vulnerable,ground,enemies,invulnerable,organic,debris,air,friend,self",
    Dur1 = 0,
    HeroDur1 = 0,
    Cost1 = 0,
    Rng1 = 9999,
})

-- #隐身
hslk_ability({
    _parent = "Apiv",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_SKILL_INVISIBLE",
    DataA1 = 0.00,
    Tip = "隐身",
    Ubertip = "隐身",
    Art = "",
    hero = 0,
    race = "other",
    Dur1 = 0,
    HeroDur1 = 0,
})

-- #回避 A/M
hslk_ability({
    _parent = "AIlf",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_SKILL_AVOID_PLUS",
    Art = "",
    levels = 2,
    DataA1 = 0,
    DataA2 = -10000000,
})
hslk_ability({
    _parent = "AIlf",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_SKILL_AVOID_MIUNS",
    Art = "",
    levels = 2,
    DataA1 = 0,
    DataA2 = 10000000,
})

H_LUA_SKILL_CD0 = hslk_ability({
    _parent = "AIgo",
    Name = "H_LUA_SKILL_ICD0",
    Tip = "H_LUA_SKILL_ICD0",
    Ubertip = "H_LUA_SKILL_ICD0",
    Effectsound = "",
    Art = "",
    TargetArt = "",
    Targetattach = "",
    DataA1 = 0,
    CasterArt = "",
    Cool = 0,
})._id

--- #选择英雄技能
H_LUA_SKILL_HERO_SELECTION = hslk_ability({
    _parent = "Aneu",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_SKILL_HERO_SELECTION",
    DataA1 = 1000.00,
    DataB1 = 4,
    DataC1 = 0,
    DataD1 = 0,
    Rng1 = 900.00,
})._id

--- #警示圈 直径64px
hslk_unit({
    _parent = "ogru",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_TEXTURE_ALERT_CIRCLE_TOKEN",
    special = 1,
    abilList = "Avul,Aloc",
    upgrade = "",
    file = "UI\\Feedback\\Target\\Target.mdl",
    unitShadow = "",
    collision = 0,
    Art = "",
    modelScale = 0.90,
    movetp = "",
    moveHeight = 0,
    moveFloor = 0.00,
    spd = 0,
    turnRate = 3.00,
    weapsOn = 0,
    race = "other",
    fused = 0,
    sight = 250,
    nsight = 250,
    Builds = "",
    upgrades = "",
    red = 255,
    blue = 0,
    green = 0,
})

--- #英雄视野 view
hslk_unit({
    _parent = "ogru",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_HERO_VIEW_TOKEN",
    special = 1,
    abilList = "Avul,AInv",
    upgrade = "",
    collision = 0.00,
    file = ".mdl",
    unitShadow = "",
    Art = "",
    movetp = "fly",
    moveHeight = 25.00,
    spd = 522,
    turnRate = 3.00,
    moveFloor = 25.00,
    weapsOn = 0,
    race = "other",
    fused = 0,
    sight = 1250,
    nsight = 1250,
    Builds = "",
    upgrades = "",
})

--- #英雄酒馆演示 tavern
hslk_unit({
    _parent = "ntav",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_HERO_TAVERN_TOKEN",
    abilList = "Avul,Asud," .. H_LUA_SKILL_HERO_SELECTION,
    Sellunits = "",
    pathTex = "",
    collision = "",
    modelScale = 0.80,
    scale = 2.80,
    uberSplat = "",
    teamColor = 12,
})

--- #英雄死亡标志
hslk_unit({
    _parent = "nban",
    Name = "H_LUA_HERO_DEATH_TOKEN",
    tilesets = "*",
    special = 1,
    hostilePal = 0,
    abilList = "Avul,Alnv,Aloc",
    upgrade = "",
    collision = 0.00,
    unitSound = 0.00,
    modelScale = 0.75,
    scale = 0.75,
    file = "h-lua\\eff_ClockRune.mdl",
    red = 255,
    blue = 255,
    green = 255,
    maxPitch = 0.00,
    maxRoll = 0.00,
    impactZ = 0.00,
    unitShadow = "",
    Art = "",
    movetp = "fly",
    spd = 0,
    turnRate = 3.00,
    moveFloor = 25.00,
    weapsOn = 0,
    race = "other",
    fused = 0,
    sight = 250,
    nsight = 250,
    Builds = "",
    upgrades = "",
})

--- #JAPI_DELAY
hslk_ability({
    _parent = "Aamk",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_JAPI_DELAY",
    Art = "",
    hero = 0,
    race = "other",
    item = 1,
    levels = 1,
    DataA1 = 0,
    DataB1 = 0,
    DataC1 = 0,
    DataD1 = 1,
})

--- #瞬逝物（地上自动捡拾物）
local fleeting = {
    { Name = "GOLD", _n = "金币", file = "Objects\\InventoryItems\\PotofGold\\PotofGold.mdl", modelScale = 1.00, moveHeight = -30 },
    { Name = "LUMBER", _n = "木材", file = "Objects\\InventoryItems\\BundleofLumber\\BundleofLumber.mdl", modelScale = 1.00, moveHeight = -30 },
    { Name = "BOOK_YELLOW", _n = "黄色书", file = "Objects\\InventoryItems\\tomeBrown\\tomeBrown.mdl", modelScale = 1.00, moveHeight = -20 },
    { Name = "BOOK_GREEN", _n = "绿色书", file = "Objects\\InventoryItems\\tomeGreen\\tomeGreen.mdl", modelScale = 1.00, moveHeight = -20 },
    { Name = "BOOK_PURPLE", _n = "紫色书", file = "Objects\\InventoryItems\\tome\\tome.mdl", modelScale = 1.00, moveHeight = -20 },
    { Name = "BOOK_BLUE", _n = "蓝色书", file = "Objects\\InventoryItems\\tomeBlue\\tomeBlue.mdl", modelScale = 1.00, moveHeight = -20 },
    { Name = "BOOK_RED", _n = "红色书", file = "Objects\\InventoryItems\\tomeRed\\tomeRed.mdl", modelScale = 1.00, moveHeight = -20 },
    { Name = "RUNE", _n = "神符", file = "Objects\\InventoryItems\\runicobject\\runicobject.mdl", modelScale = 0.80, moveHeight = -10 },
    { Name = "RELIEF", _n = "浮雕", file = "Objects\\InventoryItems\\Glyph\\Glyph.mdl", modelScale = 0.60, moveHeight = 0 },
    { Name = "EGG", _n = "蛋", file = "Objects\\InventoryItems\\ThunderLizardEgg\\ThunderLizardEgg.mdl", modelScale = 1.30, moveHeight = 20 },
    { Name = "FRAGMENT", _n = "碎片", file = "Objects\\InventoryItems\\CrystalShard\\CrystalShard.mdl", modelScale = 1.00, moveHeight = -20 },
    { Name = "QUESTION", _n = "问号", file = "Objects\\InventoryItems\\QuestionMark\\QuestionMark.mdl", modelScale = 0.60, moveHeight = 0 },
    { Name = "GRASS", _n = "荧光草", file = "Objects\\InventoryItems\\Shimmerweed\\Shimmerweed.mdl", modelScale = 0.80, moveHeight = 0 },
    { Name = "DOTA2_GOLD", _n = "Dota2赏金符", file = "h-lua\\item_Dota2.Runes.Bounty.mdl", modelScale = 0.80, moveHeight = -10 },
    { Name = "DOTA2_DAMAGE", _n = "Dota2伤害符", file = "h-lua\\item_Dota2.Runes.DoubleDamage.mdl", modelScale = 0.80, moveHeight = -10 },
    { Name = "DOTA2_CURE", _n = "Dota2恢复符", file = "h-lua\\item_Dota2.Runes.Regeneration.mdl", modelScale = 0.80, moveHeight = -10 },
    { Name = "DOTA2_SPEED", _n = "Dota2极速符", file = "h-lua\\item_Dota2.Runes.Haste.mdl", modelScale = 0.80, moveHeight = -10 },
    { Name = "DOTA2_VISION", _n = "Dota2幻象符", file = "h-lua\\item_Dota2.Runes.Illusion.mdl", modelScale = 0.80, moveHeight = -10 },
    { Name = "DOTA2_INVISIBLE", _n = "Dota2隐身符", file = "h-lua\\item_Dota2.Runes.Invisibility.mdl", modelScale = 0.80, moveHeight = -10 }
}
for _, v in ipairs(fleeting) do
    hslk_unit({
        _parent = "ogru",
        EditorSuffix = "#h-lua",
        Name = "H_LUA_ITEM_FLEETING_" .. v.Name,
        special = 1,
        abilList = "Avul,Aloc",
        upgrade = "",
        collision = 0.00,
        modelScale = v.modelScale,
        file = v.file,
        unitShadow = "",
        Art = "",
        movetp = "",
        moveHeight = v.moveHeight,
        spd = 0,
        turnRate = 0.1,
        weapsOn = 0,
        race = "other",
        fused = 0,
        sight = 0,
        nsight = 0,
    })
end

--- #树 token
hslk_unit({
    _parent = "ogru",
    EditorSuffix = "#h-lua",
    Name = "H_LUA_ENV_TREE",
    special = 1,
    abilList = "Avul,Aloc",
    upgrade = "",
    file = "h-lua\\deco_NewBirch.mdl",
    unitShadow = "ShadowFlyer",
    collision = 0,
    Art = "ReplaceableTextures\\WorldEditUI\\Doodad-Destructible.blp",
    movetp = "",
    moveHeight = 0,
    spd = 0,
    turnRate = 0,
    moveFloor = 0,
    weapsOn = 0,
    race = "other",
    fused = 0,
    sight = 0,
    nsight = 0,
    Builds = "",
    upgrades = "",
})

