---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hunzsig
--- DateTime: 2020/9/5 10:16
--- slk匹配器，方便处理slk的数据
---
--- 通用配置格式：
--- conf = {
---     {"匹配的物品名1", function(evtData) end},
---     {"匹配的物品名2", function(evtData) end},
---     ...
--- }
---


hmatcher = {
    ITEM_MATCHER = {},
    RING_MATCHER = {},
}

--- 匹配物品名
--- 触发主动使用的物品技能，在物品被使用时自动回调
--- evtData 同 hevent.onItemUsed
---@param conf table
hmatcher.item = function(conf)
    if (#conf <= 0) then
        return
    end
    for _, v in ipairs(conf) do
        if (type(v[1]) == "string" and type(v[2]) == "function") then
            table.insert(hmatcher.ITEM_MATCHER, v)
        end
    end
end

--- 匹配光环名
--- 在单位添加光环技能时自动生效
--- evtData.centerUnit
---@param conf table
hmatcher.ring = function(conf)
    if (#conf <= 0) then
        return
    end
    for _, v in ipairs(conf) do
        if (type(v[1]) == "string" and type(v[2]) == "function") then
            table.insert(hmatcher.RING_MATCHER, v)
        end
    end
end