---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hunzsig
--- DateTime: 2020/9/5 10:16
--- slk匹配器，方便处理slk的数据
---
--- 通用配置格式：
--- conf = {
---     {"匹配的物品名1", function(evtData) end},
---     {"匹配的物品名2", function(evtData) end},
---     ...
--- }
---


hmatcher = {
    ITEM_MATCHER = {}
}

--- 匹配物品名
--- 触发主动使用的物品技能，在物品被使用时自动回调
--- 可以简化onItemUsed的使用，协助管理物品
--- 适用于大众物品调用,支持正则匹配
--- evtData 同 hevent.onItemUsed
---@param conf table
hmatcher.item = function(conf)
    if (#conf <= 0) then
        return
    end
    for _, v in ipairs(conf) do
        if (type(v[1]) == "string" and type(v[2]) == "function") then
            table.insert(hmatcher.ITEM_MATCHER, v)
        end
    end
end