-- 属性系统

CONST_ATTR = {
    life = "生命",
    mana = "魔法",
    move = "移动",
    defend = "护甲",
    attack_damage_type = "攻击伤害类型",
    append_damage_type = "附身伤害类型",
    physical = "物理",
    magic = "魔法",
    fire = "火",
    soil = "土",
    water = "水",
    ice = "冰",
    wind = "风",
    light = "光",
    dark = "暗",
    wood = "木",
    thunder = "雷",
    poison = "毒",
    ghost = "鬼",
    metal = "金",
    dragon = "龙",
    insect = "虫",
    god = "神",
    attack_speed = "攻速",
    attack_speed_space = "攻击间隔",
    attack_white = "攻击力",
    attack_green = "附加攻击力",
    attack_range = "攻击范围",
    sight = "视野范围",
    str_green = "附加力量",
    agi_green = "附加敏捷",
    int_green = "附加智力",
    str_white = "本体力量",
    agi_white = "本体敏捷",
    int_white = "本体智力",
    life_back = "生命恢复",
    mana_back = "魔法恢复",
    resistance = "魔抗",
    avoid = "回避",
    aim = "命中",
    punish = "僵直",
    punish_current = "当前僵直",
    meditative = "冥想力",
    help = "救助力",
    hemophagia = "吸血",
    hemophagia_skill = "技能吸血",
    luck = "幸运",
    invincible = "无敌",
    weight = "负重",
    weight_current = "当前负重",
    damage_extent = "伤害增幅",
    damage_reduction = "伤害降低",
    damage_decrease = "伤害减免",
    damage_rebound = "反弹伤害",
    damage_rebound_oppose = "反伤抵抗",
    cure = "治疗",
    knocking_odds = "暴击几率",
    knocking_percent = "暴击伤害",
    knocking_oppose = "暴击抵抗",
    hemophagia_oppose = "吸血抵抗",
    hemophagia_skill_oppose = "技能吸血抵抗",
    buff_oppose = "强化阻碍",
    debuff_oppose = "负面抵抗",
    split_oppose = "分裂抵抗",
    punish_oppose = "僵直抵抗",
    swim_oppose = "眩晕抵抗",
    broken_oppose = "打断抵抗",
    silent_oppose = "沉默抵抗",
    unarm_oppose = "缴械抵抗",
    fetter_oppose = "缚足抵抗",
    bomb_oppose = "爆破抵抗",
    lightning_chain_oppose = "闪电链抵抗",
    crack_fly_oppose = "击飞抵抗",
    --
    natural_fire = "火强化",
    natural_soil = "土强化",
    natural_water = "水强化",
    natural_ice = "冰强化",
    natural_wind = "风强化",
    natural_light = "光强化",
    natural_dark = "暗强化",
    natural_wood = "木强化",
    natural_thunder = "雷强化",
    natural_poison = "毒强化",
    natural_ghost = "鬼强化",
    natural_metal = "金强化",
    natural_dragon = "龙强化",
    natural_insect = "虫强化",
    natural_god = "神强化",
    natural_fire_oppose = "火抗性",
    natural_soil_oppose = "土抗性",
    natural_water_oppose = "水抗性",
    natural_ice_oppose = "冰抗性",
    natural_wind_oppose = "风抗性",
    natural_light_oppose = "光抗性",
    natural_dark_oppose = "暗抗性",
    natural_wood_oppose = "风抗性",
    natural_thunder_oppose = "雷抗性",
    natural_poison_oppose = "毒抗性",
    natural_ghost_oppose = "鬼抗性",
    natural_metal_oppose = "金抗性",
    natural_dragon_oppose = "龙抗性",
    natural_insect_oppose = "虫抗性",
    natural_god_oppose = "神抗性",
    --
    xtras = "额外特效",
    --
    knocking = "暴击",
    split = "分裂",
    swim = "眩晕",
    broken = "打断",
    silent = "沉默",
    unarm = "缴械",
    fetter = "缚足",
    bomb = "爆破",
    lightning_chain = "闪电链",
    crack_fly = "击飞",
    --
    odds = "几率",
    percent = "比例",
    val = "数值",
    dur = "持续时间",
    qty = "数量",
    radius = "范围",
    rate = "比率",
    distance = "距离",
    height = "高度",
    -- 本身是在player实现
    gold_ratio = "黄金获得率",
    lumber_ratio = "木头获得率",
    exp_ratio = "经验获得率",
    sell_ratio = "售卖比率"
}

CONST_ATTR_KEYS = {
    "life",
    "mana",
    "move",
    "defend",
    "attack_damage_type",
    "append_damage_type",
    "attack_speed",
    "attack_speed_space",
    "attack_white",
    "attack_green",
    "attack_range",
    "sight",
    "str_green",
    "agi_green",
    "int_green",
    "str_white",
    "agi_white",
    "int_white",
    "life_back",
    "mana_back",
    "resistance",
    "avoid",
    "aim",
    "punish",
    "punish_current",
    "meditative",
    "help",
    "hemophagia",
    "hemophagia_skill",
    "luck",
    "invincible",
    "weight",
    "weight_current",
    "damage_extent",
    "damage_reduction",
    "damage_decrease",
    "damage_rebound",
    "damage_rebound_oppose",
    "cure",
    "knocking_odds",
    "knocking_percent",
    "knocking_oppose",
    "hemophagia_oppose",
    "hemophagia_skill_oppose",
    "split_oppose",
    "punish_oppose",
    "swim_oppose",
    "broken_oppose",
    "silent_oppose",
    "unarm_oppose",
    "fetter_oppose",
    "bomb_oppose",
    "lightning_chain_oppose",
    "crack_fly_oppose",
    "natural_fire",
    "natural_soil",
    "natural_water",
    "natural_ice",
    "natural_wind",
    "natural_light",
    "natural_dark",
    "natural_wood",
    "natural_thunder",
    "natural_poison",
    "natural_ghost",
    "natural_metal",
    "natural_dragon",
    "natural_insect",
    "natural_god",
    "natural_fire_oppose",
    "natural_soil_oppose",
    "natural_water_oppose",
    "natural_ice_oppose",
    "natural_wind_oppose",
    "natural_light_oppose",
    "natural_dark_oppose",
    "natural_wood_oppose",
    "natural_thunder_oppose",
    "natural_poison_oppose",
    "natural_ghost_oppose",
    "natural_metal_oppose",
    "natural_dragon_oppose",
    "natural_insect_oppose",
    "natural_god_oppose",
    "xtras",
    "gold_ratio",
    "lumber_ratio",
    "exp_ratio",
    "sell_ratio"
}

CONST_ATTR_BUFF_KEYS = {
    "on",
    "action",
    "odds",
    "percent",
    "val",
    "dur",
    "qty",
    "radius",
    "rate",
    "distance",
    "height",
    "lightning_type",
    "effect",
    "effectEnum",
    "damageSrc",
    "damageType",
}
