-- 附魔系统

CONST_ENCHANT_CONF = {
    { value = "physical", label = "物理" },
    { value = "magic", label = "魔法" },
    { value = "fire", label = "火" },
    { value = "flame", label = "焰" },
    { value = "soil", label = "土" },
    { value = "rock", label = "岩" },
    { value = "sand", label = "砂" },
    { value = "lava", label = "熔" },
    { value = "water", label = "水" },
    { value = "ice", label = "冰" },
    { value = "storm", label = "岚" },
    { value = "wind", label = "风" },
    { value = "light", label = "光" },
    { value = "dark", label = "暗" },
    { value = "wood", label = "木" },
    { value = "grass", label = "草" },
    { value = "thunder", label = "雷" },
    { value = "electric", label = "电" },
    { value = "metal", label = "金" },
    { value = "iron", label = "铁" },
    { value = "steel", label = "钢" },
    { value = "dragon", label = "龙" },
    { value = "insect", label = "虫" },
    { value = "poison", label = "毒" },
    { value = "evil", label = "邪" },
    { value = "ghost", label = "鬼" },
    { value = "god", label = "神" },
    { value = "holy", label = "圣" },
    --你可以使用 henchant.supply 方法拓展自定义附魔属性
}

CONST_ENCHANT = {
    attack_enchant = "攻击伤害类型",
    append_enchant = "附身伤害类型",
    physical = "物理",
    magic = "魔法",
    fire = "火",
    soil = "土",
    water = "水",
    ice = "冰",
    wind = "风",
    light = "光",
    dark = "暗",
    wood = "木",
    thunder = "雷",
    poison = "毒",
    ghost = "鬼",
    metal = "金",
    dragon = "龙",
    insect = "虫",
    god = "神",
    e_fire = "火强化",
    e_soil = "土强化",
    e_water = "水强化",
    e_ice = "冰强化",
    e_wind = "风强化",
    e_light = "光强化",
    e_dark = "暗强化",
    e_wood = "木强化",
    e_thunder = "雷强化",
    e_poison = "毒强化",
    e_ghost = "鬼强化",
    e_metal = "金强化",
    e_dragon = "龙强化",
    e_insect = "虫强化",
    e_god = "神强化",
    e_fire_oppose = "火抗性",
    e_soil_oppose = "土抗性",
    e_water_oppose = "水抗性",
    e_ice_oppose = "冰抗性",
    e_wind_oppose = "风抗性",
    e_light_oppose = "光抗性",
    e_dark_oppose = "暗抗性",
    e_wood_oppose = "风抗性",
    e_thunder_oppose = "雷抗性",
    e_poison_oppose = "毒抗性",
    e_ghost_oppose = "鬼抗性",
    e_metal_oppose = "金抗性",
    e_dragon_oppose = "龙抗性",
    e_insect_oppose = "虫抗性",
    e_god_oppose = "神抗性",
}