CONST_SLK = {
    item = {
        "abiList", "Requires", "Requiresamount", "Name", "Description", "Tip",
        "Ubertip", "Hotkey", "Art", "scale", "file", "Buttonpos1", "Buttonpos2",
        "selSize", "colorR", "colorG", "colorB", "armor", "Level", "oldLevel", "class",
        "goldcost", "lumbercost", "HP", "stockStart", "stockRegen", "stockMax", "prio",
        "cooldownID", "ignoreCD", "morph", "drop", "powerup", "sellable", "pawnable",
        "droppable", "pickRandom", "uses", "perishable", "usable",
    },
    unit = {
        "Name", "Description", "Tip", "Ubertip", "Hotkey", "level", "race", "type",
        "goldcost", "lumbercost", "manaN", "regenMana", "mana0", "HP", "regenHP", "regenType", "fmade", "fused", "stockStart", "stockRegen",
        "sight", "nsight", "buffRadius", "buffType", "collision", "modelScale", "file", "fileVerFlags", "scaleBull", "scale", "selZ", "selCircOnWater",
        "red", "green", "blue", "occH", "maxPitch", "maxRoll", "impactZ", "impactSwimZ", "launchX", "launchY", "launchZ", "launchSwimZ",
        "unitSound", "RandomSoundLabel", "MovementSoundLabel", "LoopingSoundFadeOut", "LoopingSoundFadeIn", "auto", "abilList",
        "Sellitems", "Sellunits", "Markitems", "Builds", "Buttonpos1", "Buttonpos2", "Art", "Specialart",
        "unitShadow", "buildingShadow", "shadowH", "shadowW", "shadowX", "shadowY", "shadowOnWater",
        "death", "deathType", "movetp", "moveHeight", "moveFloor", "spd", "maxSpd", "minSpd", "turnRate",
        "acquire", "minRange", "weapsOn", "Missileart", "Missilespeed", "Missilearc", "MissileHoming", "targs1", "atkType1", "weapTp1", "weapType1",
        "spillRadius1", "spillDist1", "damageLoss1", "showUI1", "backSw1", "dmgpt1", "rangeN1", "RngBuff1", "dmgplus1", "dmgUp1", "sides1", "dice1",
        "splashTargs1", "cool1", "Farea1", "targCount1", "Qfact1", "Qarea1", "Hfact1", "Harea1", "Missileart2", "Missilespeed2",
        "Missilearc2", "MissileHoming2", "targs2", "atkType2", "weapTp2", "weapType2", "spillRadius2", "spillDist2", "damageLoss2",
        "showUI2", "backSw2", "dmgpt2", "rangeN2", "RngBuff2", "dmgplus2", "dmgUp2", "sides2", "dice2", "splashTargs2", "cool2", "Farea2",
        "targCount2", "Qfact2", "Qarea2", "Hfact2", "Harea2", "defType", "defUp", "def", "armor", "targType", "Propernames", "nameCount",
        "Awakentip", "Revivetip", "Primary", "STR", "STRplus", "AGI", "AGIplus", "INT", "INTplus", "heroAbilList", "hideHeroMinimap", "hideHeroBar",
        "hideHeroDeathMsg", "Requiresacount", "Requires1", "Requires2", "Requires3", "Requires4", "Requires5", "Requires6", "Requires7", "Requires8",
        "Reviveat", "Revive", "Trains", "Upgrade", "requirePlace", "preventPlace", "requireWaterRadius", "pathTex", "uberSplat", "nbrandom",
        "nbmmlcon", "canBuildOn", "isBuildOn", "tilesets", "special", "campaign", "inEditor", "dropItems", "hostilePal", "useClickHelper",
        "tilesetSpecific", "Requires", "Requiresamount", "DependencyOr", "Researches", "upgrades", "EditorSuffix", "Casterupgradename",
        "Casterupgradetip", "Castrerupgradeart", "ScoreScreenIcon", "animProps", "Attachmentanimprops", "Attachmentlinkprops",
        "Boneprops", "castpt", "castbsw", "blend", "run", "walk", "propWin", "orientInterp", "teamColor", "customTeamColor",
        "elevPts", "elevRad", "fogRad", "fatLOS", "repulse", "repulsePrio", "repulseParam", "repulseGroup", "isbldg", "bldtm",
        "bountyplus", "bountysides", "bountydice", "goldRep", "lumberRep", "reptm", "lumberbountyplus", "lumberbountysides",
        "lumberbountydice", "cargoSize", "stockMax", "hideOnMinimap", "points", "prio", "formation", "canFlee", "canSleep",
    },
    ability = {
        "checkDep", "Requires", "Requiresamount", "Effectsound", "Effectsoundlooped", "EditorSuffix",
        "Name", "Untip", "Unubertip", "Tip", "Ubertip", "Researchtip", "Researchubertip",
        "Unorder", "Order", "Orderoff", "Unhotkey", "Hotkey", "Researchhotkey",
        "UnButtonpos1", "UnButtonpos2", "Buttonpos1", "Buttonpos2", "Researchbuttonpos1", "Researchbuttonpos2",
        "Unart", "Art", "SpecialArt", "Specialattach", "Missileart", "Missilespeed", "Missilearc", "MissileHoming",
        "LightningEffect", "EffectArt", "TargetArt", "Targetattachcount", "Targetattach",
        "Targetattach1", "Targetattach2", "Targetattach3", "Targetattach4", "Targetattach5",
        "Areaeffectart", "Animnames", "CasterArt", "Casterattachcount", "Casterattach", "Casterattach1",
        "hero", "item", "race", "levels", "reqLevel", "priority", "BuffID1", "EfctID1", "Tip1",
        "Ubertip1", "targs1", "DataA1", "DataB1", "DataC1", "DataD1", "DataE1", "DataF1", "Cast1",
        "Cool1", "Dur1", "HeroDur1", "Cost1", "Rng1", "Area1",
    },
}

CONST_HSLK = {
    item = { "_id", "_type", "_parent", "_overlie", "_weight", "_active", "_passive", "_attr", "_attr_txt", "_ring", "_cooldown", "_shadow" },
    unit = { "_id", "_type", "_parent", "_attr" },
    ability = { "_id", "_type", "_parent", "_desc", "_attr", "_attr_txt", "_ring", "_cooldown" },
}
