--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-cli)

-- 调试自动去除迷雾
henv.setFogStatus(isDebugging() == false, isDebugging() == false)

-- 设定玩家
hplayer.qty_max = 1 -- 最大玩家数
hplayer.convert_ratio = 1000000 -- 换算比率，100金 -> 1木

-- 设定敌军
henemy.set("怪物", nil, { 2 }, false)

--- 设定获得黄金木头特效
hevent.onPlayerResourceChange(function(evtData)
    if (evtData.triggerUnit ~= nil and evtData.value > 0) then
        local u = evtData.triggerUnit
        local val = math.floor(evtData.value)
        if (evtData.type == 'gold') then
            htextTag.style(htextTag.create2Unit(u, "+" .. val .. " 金", 6, "ffcc00", 1, 1.70, 60.00), "toggle", 0, 0.20)
            hsound.voice2Unit(cg.gg_snd_ReceiveGold, 100, u)
        elseif (evtData.type == 'lumber') then
            htextTag.style(htextTag.create2Unit(u, "+" .. val .. " 木", 7, "80ff80", 1, 1.70, 60.00), "toggle", 0, 0.20)
            hsound.voice2Unit(cg.gg_snd_BundleOfLumber, 100, u)
        end
    end
end)

--- 经验获取漂浮字
onExpTextTag = function(u)
    hevent.onExp(u, function(evtData)
        htextTag.style(htextTag.create2Unit(
            evtData.triggerUnit,
            "+" .. evtData.value .. " 经验", 7, "c4c4ff", 1, 1.70, 60.00
        ), "toggle", 0, 0.20)
    end)
end