--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-cli)

local startTrigger = cj.CreateTrigger()
cj.TriggerRegisterTimerEvent(startTrigger, 0.1, false)
cj.TriggerAddAction(startTrigger, function()
    cj.DisableTrigger(startTrigger)
    cj.DestroyTrigger(startTrigger)

    echo("hello world!")
    print_mb("你好！世界！")

end)
