--- Generated by h-lua-cli(https://github.com/hunzsig-warcraft3/h-lua-cli)

-- h-lua main function 主函数入口
-- The game starts here 游戏从main函数开始运行
function main()
    print("hello world!")
    echo("你好，世界！")
end